name: Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Step
      run: echo "Building the frontend..."

    - name: Set up SSH
      run: |
        # Write the SSH private key to a file
        echo "${{ secrets.KEY_PAIR }}" > ~/Obelion_task.pem
        # Ensure the private key has the correct permissions
        chmod 600 ~/Obelion_task.pem

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Frontend to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.FRONTEND_IP }}
        echo "Deploying frontend"
        cd /path/to/your/frontend
        git pull origin master
        npm install
        npm run build

        # Add your actual deployment commands here
        EOF
