name: Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Step
      run: echo "Building the frontend..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        # Save the private key from GitHub secrets to a file
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/ec2_key.pem
        chmod 600 ~/ec2_key.pem

    - name: Deploy Frontend to EC2
      run: |
        ssh -i ~/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.FRONTEND_IP }} << EOF
          echo "Deploying uptime-kuma"
          # # Update package lists
          # sudo apt update
          # # Install Node.js and npm
          # curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          # sudo apt-get install -y nodejs
          # # Clone uptime-kuma repo if not exists
          # if [ ! -d "/home/ubuntu/uptime-kuma" ]; then
          #   git clone https://github.com/Bogzy-Medhat/uptime-kuma.git /home/ubuntu/uptime-kuma
          # fi
          # cd /home/ubuntu/uptime-kuma
          # git pull origin master
          # npm install
          # npm run build
        EOF
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        FRONTEND_IP: ${{ secrets.FRONTEND_IP }}
