name: Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Step
      run: echo "Building the frontend..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        # Save the private key from GitHub secrets to a file
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/ec2_key.pem
        # Change permissions to ensure the private key is secure
        chmod 600 ~/ec2_key.pem

    - name: Deploy Frontend to EC2
      run: |
        # SSH into the EC2 instance and run the deployment commands
        ssh -i ~/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.FRONTEND_IP }} << EOF
          echo "Deploying frontend"
          cd /path/to/your/frontend
          git pull origin master
          npm install
          npm run build
        EOF
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        FRONTEND_IP: ${{ secrets.FRONTEND_IP }}
